Implement integration test
lordksix/blog-by-rails pull request #8
Opened 2023-08-29 21:13 UTC by lordksix

In this PR, the changes are as follows: 
  - [ ] Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
  previous
![Screenshot from 2023-08-29 16-09-40](https://github.com/lordksix/blog-by-rails/assets/121689749/846617bc-d8e7-40c2-96d1-9af79edfb4eb)
  new
![Screenshot from 2023-08-29 16-08-51](https://github.com/lordksix/blog-by-rails/assets/121689749/7af276c3-1758-40e1-b936-6de87820ef21)

  - [ ] Implement integration test for user index page
  - [ ] Implement integration test for user show page
  - [ ] Implement integration test for user post index page:
  - [ ] Implement integration test for post show page:

2023-08-29 22:38 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi Team 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Write integration tests with Capybara gem.
- ✔️ Secure app from n+1 problems.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 22:38 UTC, abdulhamiid commented on spec/views/users/user_index_spec.rb
>      )
According to the project requirements, please use Capybara to write integration tests for the user show page: 🤗🛠

![image](https://github.com/lordksix/blog-by-rails/assets/78251927/a46d044a-f84a-47a4-9892-895a75704e4f)

I suggest that you implement that in a separate file so as to make sure that individual parts of your application work. 💪

2023-08-29 22:38 UTC, abdulhamiid commented on spec/views/posts/post.show_spec.rb
> +end
According to the project requirements, you have written an integration test for the post-show page 👍. 

Please write integration tests for the post index page also: 🤗🛠

![image](https://github.com/lordksix/blog-by-rails/assets/78251927/0b8ca043-d832-46f0-87c3-074adbd1443b)

- I suggest that you implement that in a separate file. 💪

- here's a [capybara cheat sheet](https://gist.github.com/zhengjia/428105) you can use. 🤗

2023-08-29 23:51 UTC, lordksix commented on spec/views/users/user_index_spec.rb
>      )
The tests for user index page were transfer to spec/view/user/index.html.erb_spec.rb so this is an old and incomplet version of that file

2023-08-29 23:52 UTC, lordksix commented on spec/views/posts/post.show_spec.rb
> +end
The tests for post show page were transfer to spec/view/post/show.html.erb_spec.rb so this is an old and incomplet version of that file

2023-08-30 00:19 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @lordksix, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 00:21 UTC, merged